export const ApiEndpoint = {
  SERVER_PlayerExist: '/api/server/playerExist',
  SERVER_Available: '/api/server/available',
  SERVER_Galaxy_Available: '/api/server/galaxy/available',
  AUTH_ResetPassword: '/api/auth/reset-password',
  AUTH_ForgotPassword: '/api/auth/forgot-password',
  AUTH_CheckResetPasswordToken: '/api/auth/token/checkResetPasswordToken',
  AUTH_Validate: '/api/auth/validate',
  AUTH_Login: '/api/auth/login',
  AUTH_Register: '/api/auth/register',
  ACTIVITY_FriendGroupPlayer: '/api/activity/friendgroup/player',
  ACTIVITY_FriendGroupGalaxy: '/api/activity/friendgroup/galaxy',
  ACTIVITY_SelfPlayer: '/api/activity/self/player',
  ACTIVITY_SelfGalaxy: '/api/activity/self/galaxy',
  ACTIVITY_GlobalPlayer: '/api/activity/global/player',
  ACTIVITY_GlobalGalaxy: '/api/activity/global/galaxy',
  USER_Update: '/api/user/update',
  USER_Contact: '/api/message/user/contact',
  USER_BugReport: '/api/message/user/bugReport',
  USER_UpdatePassword: '/api/user/update/password'
};
