export const ApiEndpoint = {
  SERVER_PlayerExist: '/server/playerExist',
  SERVER_Available: '/server/available',
  SERVER_Galaxy_Available: '/server/galaxy/available',
  AUTH_ResetPassword: '/auth/reset-password',
  AUTH_ForgotPassword: '/auth/forgot-password',
  AUTH_CheckResetPasswordToken: '/auth/token/checkResetPasswordToken',
  AUTH_Validate: '/auth/validate',
  AUTH_Login: '/auth/login',
  AUTH_Register: '/auth/register',
  ACTIVITY_FriendGroupPlayer: '/activity/friendgroup/player',
  ACTIVITY_FriendGroupGalaxy: '/activity/friendgroup/galaxy',
  ACTIVITY_SelfPlayer: '/activity/self/player',
  ACTIVITY_SelfGalaxy: '/activity/self/galaxy',
  ACTIVITY_GlobalPlayer: '/activity/global/player',
  ACTIVITY_GlobalGalaxy: '/activity/global/galaxy',
};
