export const ApiEndpoint = {
  DATA_PlayerExistInServer: '/data/playerExistInServer',
  DATA_AvailableServers: '/data/availableServers',
  AUTH_ResetPassword: '/auth/reset-password',
  AUTH_ForgotPassword: '/auth/forgot-password',
  AUTH_CheckResetPasswordToken: '/auth/token/checkResetPasswordToken',
  AUTH_Validate: '/auth/validate',
  AUTH_Login: '/auth/login',
  AUTH_Register: '/auth/register',
  PLAYER_ActivityFriendGroup: '/player/activity/friendgroup',
  PLAYER_ActivityFriendGroupAll: '/player/activity/friendgroup/all',
  PLAYER_ActivityFriendGroupGalaxy: '/player/activity/friendgroup/galaxy',
  PLAYER_ActivitySelf: '/player/activity/self',
  PLAYER_ActivitySelfAll: '/player/activity/self/all',
  PLAYER_ActivitySelfGalaxy: '/player/activity/self/galaxy',
  PLAYER_ActivityGlobal: '/player/activity/global',
  PLAYER_ActivityGlobalAll: '/player/activity/global/all',
  PLAYER_ActivityGlobalGalaxy: '/player/activity/global/galaxy',
};
