export const RoutesEndpoint = {
  '404': '/404',
  HOME: '/',
  DASHBOARD: '/dashboard',
  HOWTOSTART: '/how-to-start',
  GETHELP: '/get-help',
  PLAYER_Activity: '/activity/player',
  PLAYER_Galaxy: '/activity/galaxy',
  PLAYER_Report_Spy: '/report/spy',
  DATA_Colonial: '/data/colonial',
  DATA_Military: '/data/military',
  ACCOUNT_Profile: '/account',
  ACCOUNT_Security: '/account/security',
  ACCOUNT_Premium: '/account/premium',
  ACCOUNT_DashboardSettings: '/account/dashboardSettings',
  ACCOUNT_Contact: '/account/contact',
  ACCOUNT_FriendList: '/account/friendList',
  ACCOUNT_GroupManagement: '/account/groupManagement',
  ACCOUNT_BugReport: '/account/bugReport',
  AUTH_Login: '/auth/login',
  AUTH_Register: '/auth/register',
  AUTH_ValidateAccount: '/auth/validate-account/:verificationLink',
  AUTH_ForgetPassword: '/auth/forgot-password',
  AUTH_ResetPassword: '/auth/reset-password/:token',
};
